### ISSUE TITLE
执行报错呢？

### ISSUE THREAD

**Issue by wentixiaogege** [chengsyuan/KDD-Multimodalities-Recall#4]
<ipython-input-19-ede967710d87> in predict(self, tokens, attn1, rois, attn2)
     16         img_emb = self.img_enc(rois.squeeze(), attn2.squeeze())
     17 #         sim = txt_emb.mm(img_emb.T)
---> 18         sim = torch.mm(txt_emb,img_emb.T)
     19         return sim
     20 

TypeError: mm(): argument 'input' (position 1) must be Tensor, not str
# 疑问：
debug 到这个地方 发现self.text_enc 得到的确实是string。。 
求解

**Comment by chengxuanying** [comment]
print出来看看？po在下面

**Comment by wentixiaogege** [comment]
```
class TextEncoder(nn.Module):
    def __init__(self):
        super(TextEncoder, self).__init__()
        self.bert_text = bert_text
    def forward(self, tokens, attns):
        ss = self.bert_text(
            input_ids=tokens, 
            attention_mask=attns)
        sequence_output, pooled_output = ss['last_hidden_state'],ss['pooler_output'] # 版本问题么？我改成这样可以了
        return pooled_output
```

**Comment by chengxuanying** [comment]
估计是huggingface升级了，api总变
anyway，能跑起来就好

**Comment by wentixiaogege** [comment]
请问，当时跑了多少epoch？好像不是预先设置的个数

**Comment by wentixiaogege** [comment]
可以关闭这个isusue了哈
